apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
  labels:
    app: backend-api
spec:
  replicas: 1  # Número de réplicas de tu aplicación
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: cesarvazquezmaypo/my-api:latest  # Imagen de Docker Hub
        ports:
        - containerPort: 5000  # Puerto en el que corre Flask (ajusta si es necesario)
        env:
        - name: FLASK_APP
          value: app.py
        - name: FLASK_ENV
          value: development
        