apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  labels:
    app: frontend-app
spec:
  type:  NodePort  # Cambia a ClusterIP si no necesitas exponerlo públicamente
  ports:
  - port: 80
    targetPort: 80  # Mapea el puerto del servicio al puerto del contenedor
  selector:
    app: frontend-app
