name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build and push Docker Image for API
    - name: Build and Push API Image
      uses: docker/build-push-action@v4
      with:
        context: ./app/api
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-api:latest

    # 4. Build and push Docker Image for Web
    - name: Build and Push Web Image
      uses: docker/build-push-action@v4
      with:
        context: ./app/web
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-web:latest

    # 5. Build and push Docker Image for Proxy
    - name: Build and Push Proxy Image
      uses: docker/build-push-action@v4
      with:
        context: ./app/proxy
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-proxy:latest

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build-and-push
  
    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3
  
    # 2. Set up Google Cloud SDK
    - name: Set up GCP SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
  
    # 3. Update Google Cloud SDK
    - name: Update Google Cloud SDK
      run: |
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk
  
    # 4. Install GKE Auth Plugin
    - name: Install GKE Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin
  
    # 5. Authenticate with GKE
    - name: Authenticate with GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}
  
    # 6. Apply Kubernetes manifests
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/overlays/dev/backend
        kubectl apply -f k8s/overlays/dev/frontend
        kubectl apply -f k8s/overlays/dev/proxy

