name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Build and push Docker Image for API
    - name: Build and Push API Image
      uses: docker/build-push-action@v4
      with:
        context: ./app/api
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-api:latest

    # 4. Build and push Docker Image for Web
    - name: Build and Push Web Image
      uses: docker/build-push-action@v4
      with:
        context: ./app/web
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-web:latest

    # 5. Build and push Docker Image for Proxy
    - name: Build and Push Proxy Image
      uses: docker/build-push-action@v4
      with:
        context: ./app/proxy
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-proxy:latest
