name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Set version tag
    - name: Set Image Version
      id: vars
      run: echo "VERSION=$(date +'%Y%m%d')-${{ github.run_number }}" >> $GITHUB_ENV

    # 4. Build and push Docker Image for API
    - name: Build and Push API Image
      uses: docker/build-push-action@v4
      with:
        context: ./app/api
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/my-api:latest
          ${{ secrets.DOCKER_USERNAME }}/my-api:${{ env.VERSION }}

    # 5. Build and push Docker Image for Web
    - name: Build and Push Web Image
      uses: docker/build-push-action@v4
      with:
        context: ./app/web
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/my-web:latest
          ${{ secrets.DOCKER_USERNAME }}/my-web:${{ env.VERSION }}

    # 6. Build and push Docker Image for Proxy
    - name: Build and Push Proxy Image
      uses: docker/build-push-action@v4
      with:
        context: ./app/proxy
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/my-proxy:latest
          ${{ secrets.DOCKER_USERNAME }}/my-proxy:${{ env.VERSION }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Authenticate with Google Cloud
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    # 3. Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # 4. Install GKE Auth Plugin
    - name: Install GKE Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    # 5. Authenticate with GKE
    - name: Authenticate with GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}

    # 6. Apply Kubernetes manifests
    - name: Apply Kubernetes manifests
      run: |
        kubectl set image deployment/backend-api-deployment backend-api=${{ secrets.DOCKER_USERNAME }}/my-api:${{ env.VERSION }}
        kubectl set image deployment/frontend-app frontend-app=${{ secrets.DOCKER_USERNAME }}/my-web:${{ env.VERSION }}
        kubectl set image deployment/nginx-proxy-rox nginx-proxy=${{ secrets.DOCKER_USERNAME }}/my-proxy:${{ env.VERSION }}
